repos:
  - repo: local
    hooks:
      - id: nixpkgs-fmt
        name: nixpkgs-fmt
        entry: nixpkgs-fmt
        language: system
        types: [nix]

      - id: statix
        name: statix
        entry: bash -c 'for file in "$@"; do statix check "$file"; done' --
        language: system
        types: [nix]

      - id: deadnix
        name: deadnix
        entry: deadnix
        language: system
        types: [nix]
