repos:
  - repo: local
    hooks:
      - id: nixpkgs-fmt
        name: nixpkgs-fmt
        description: Format nix files
        entry: nixpkgs-fmt
        language: system
        files: \.nix$
        pass_filenames: true

      - id: statix
        name: statix
        description: Lint nix files
        entry: statix check
        language: system
        files: \.nix$
        pass_filenames: false

      - id: deadnix
        name: deadnix
        description: Find dead code in nix files
        entry: deadnix
        language: system
        files: \.nix$
        pass_filenames: true

  # Only run home-manager in post-commit to avoid the error during pre-commit
  - repo: local
    hooks:
      - id: home-manager-path
        name: home-manager-path
        description: Update home-manager environment
        entry: home-manager switch --flake .#self
        language: system
        stages: [post-commit]
        pass_filenames: false